/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    Gallary: typeof import('./src/components/gallary.vue')['default']
    HeaderMenu: typeof import('./src/components/headerMenu.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    MainChatRoom: typeof import('./src/components/mainChatRoom.vue')['default']
    Message: typeof import('./src/components/message.vue')['default']
    MessageRight: typeof import('./src/components/messageRight.vue')['default']
    OnlineUser: typeof import('./src/components/onlineUser.vue')['default']
    PrivateChatRoom: typeof import('./src/components/privateChatRoom.vue')['default']
    RightBottomWindow: typeof import('./src/components/rightBottomWindow.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/sideBar.vue')['default']
  }
}
