/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FileDownload: typeof import('./src/components/FileDownload.vue')['default']
    FileUpload: typeof import('./src/components/FileUpload.vue')['default']
    Gallary: typeof import('./src/components/Gallary.vue')['default']
    HeaderMenu: typeof import('./src/components/HeaderMenu.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    MainChatRoom: typeof import('./src/components/MainChatRoom.vue')['default']
    Message: typeof import('./src/components/Message.vue')['default']
    MessageRight: typeof import('./src/components/MessageRight.vue')['default']
    OnlineUser: typeof import('./src/components/OnlineUser.vue')['default']
    PrivateChatRoom: typeof import('./src/components/PrivateChatRoom.vue')['default']
    RightBottomWindow: typeof import('./src/components/RightBottomWindow.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    SideBarMini: typeof import('./src/components/SideBarMini.vue')['default']
    SubHeader: typeof import('./src/components/SubHeader.vue')['default']
    UserInfo: typeof import('./src/components/UserInfo.vue')['default']
  }
}
